// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikvoxnwbdkethbakkvxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrdm94bndiZGtldGhiYWtrdnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODg1NDgsImV4cCI6MjA2NTQ2NDU0OH0.aFN1_uiSwSZVmjK4GmQs1cmBhIkK0Nm7yTRmZQh4jQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);